image: julia:1.6

tests:
  script:
    - apt-get update
    - apt-get -y install git
    - julia -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()))'
    - julia -e 'using Pkg; Pkg.test("SolidState", coverage=true)'
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; cl, tl = get_summary(process_folder()); println("(", cl/tl*100, "%) covered")'

pages:
  stage: deploy
  before_script:
    - apt update
    - apt install --assume-yes make gcc git
    - git config --global url."https://${CI_USERNAME}:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "git@gitlab.com:"
    - git submodule sync && git submodule update --init
  script:
    - julia -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));'
    - julia -e 'using Pkg; Pkg.add("Documenter"); Pkg.add("Literate"); include(joinpath("docs", "make.jl"));'
    - cd docs/
    - mv build ../public/
  artifacts:
    paths:
      - public
  only:
    - master
